target: 127.0.0.1
verbose: true
plugins:
  - discovery
  - scanner
  - vuln
  - credaudit
  - exploit_scanner
  - system_auditor
  - spider
  - vuln_verifier
  - adversary_sim
  - web_fuzzer
  - protocol_auditor
  - cloud_auditor
  - takeover_auditor
  - leak_auditor
  - baseline_auditor
  - foothold
  - remote_exec
  - memory_phantom
  - context_trigger
  - messaging_auditor
