target: 127.0.0.1
verbose: true
plugins:
  - discovery
  - scanner
  - vuln
  - credaudit
  - exploit_scanner
  - system_auditor
  - spider
  - vuln_verifier
  - adversary_sim
  - web_fuzzer
  - protocol_auditor
  - cloud_auditor
  - takeover_auditor
  - leak_auditor
  - baseline_auditor
  - foothold
  - remote_exec
  - advanced_info
  - swarm_orchestrator
  - morphing_backdoor
  - secret_harvester
  - memory_phantom
  - context_trigger
  - messaging_auditor
  - polymorphic_plugin
  - stegano_plugin
  - polyglot_plugin
  - behavioral_ai
  - av_evasion
  - lateral_pivoter
  - supply_chain_auditor
  - kernel_auditor
  - osint_master
  - delivery_suite
